### ISSUE TITLE
feature request: highlight the whole square 

### ISSUE THREAD

**Issue by liabri** [zohnannor/yawc#9]
It would be aesthetically nicer if the whole square was highlighted rather than just the letter, I think it should be possible if I understand how TUIs work :)

**Comment by zohnannor** [comment]
I agree, it would be a lot cooler, I thought of that as well. However, these squares are just [symbols](https://en.wikipedia.org/wiki/Box-drawing_character): 

```
             ┌───┬───┬───┬───┬───┐             
             │   │   │   │   │   │             
             ├───┼───┼───┼───┼───┤             
             │   │   │   │   │   │             
             ├───┼───┼───┼───┼───┤             
             │   │   │   │   │   │             
             ├───┼───┼───┼───┼───┤             
             │   │   │   │   │   │             
             ├───┼───┼───┼───┼───┤             
             │   │   │   │   │   │             
             ├───┼───┼───┼───┼───┤             
             │   │   │   │   │   │             
             └───┴───┴───┴───┴───┘             
   ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐   
   │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │   
   └─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┘   
     │ A │ S │ D │ F │ G │ H │ J │ K │ L │     
     └─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┘     
       │ Z │ X │ C │ V │ B │ N │ M │           
       └───┴───┴───┴───┴───┴───┴───┘           
```

and coloring some parts of, for example, `┬` is not possible (AFAIK). Thanks for the suggestion though! :)

**Comment by liabri** [comment]
Yeah I was aware of that, but was hoping it'd line up nicer but I suppose it doesn't. There's definitely a way but it might be way too much effort for what it's worth sadly :/

**Comment by zohnannor** [comment]
I updated it and now it colors the two spaces on the sides of the letter :)
